"""initial

Revision ID: 9f1382a9c502
Revises:
Create Date: 2026-03-17 08:32:02.936375

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f1382a9c502"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                "cancelled",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column("agent_count", sa.Integer(), nullable=False),
        sa.Column("round_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("max_total_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("handle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("persona_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "persona_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("stance_bias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verbosity_bias", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "skepticism_bias", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_handle"), "agents", ["handle"], unique=False)
    op.create_index(op.f("ix_agents_run_id"), "agents", ["run_id"], unique=False)
    op.create_table(
        "analysis_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("predicted_engagement", sa.Float(), nullable=False),
        sa.Column("predicted_shareability", sa.Float(), nullable=False),
        sa.Column("predicted_conversion_signal", sa.Float(), nullable=False),
        sa.Column("predicted_trust", sa.Float(), nullable=False),
        sa.Column("top_positive_themes", sa.JSON(), nullable=True),
        sa.Column("top_negative_themes", sa.JSON(), nullable=True),
        sa.Column("top_objections", sa.JSON(), nullable=True),
        sa.Column(
            "recommended_rewrite", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_reports_run_id"), "analysis_reports", ["run_id"], unique=True
    )
    op.create_table(
        "run_seeds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cta", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audience_segments", sa.JSON(), nullable=True),
        sa.Column(
            "controversy_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_seeds_run_id"), "run_seeds", ["run_id"], unique=False)
    op.create_table(
        "follows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("follower_agent_id", sa.Uuid(), nullable=False),
        sa.Column("followed_agent_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_follows_followed_agent_id"),
        "follows",
        ["followed_agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_follows_follower_agent_id"),
        "follows",
        ["follower_agent_id"],
        unique=False,
    )
    op.create_index(op.f("ix_follows_run_id"), "follows", ["run_id"], unique=False)
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum("agent_action", "final_analysis", name="llmcallstage"),
            nullable=False,
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_calls_run_id"), "llm_calls", ["run_id"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("author_agent_id", sa.Uuid(), nullable=False),
        sa.Column("parent_post_id", sa.Uuid(), nullable=True),
        sa.Column("root_post_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "stance",
            sa.Enum(
                "supportive",
                "skeptical",
                "neutral",
                "critical",
                "curious",
                name="stance",
            ),
            nullable=False,
        ),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("reply_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_posts_author_agent_id"), "posts", ["author_agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_posts_root_post_id"), "posts", ["root_post_id"], unique=False
    )
    op.create_index(
        op.f("ix_posts_round_number"), "posts", ["round_number"], unique=False
    )
    op.create_index(op.f("ix_posts_run_id"), "posts", ["run_id"], unique=False)
    op.create_table(
        "interactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "interaction_type",
            sa.Enum("like", "follow", name="interactiontype"),
            nullable=False,
        ),
        sa.Column("target_post_id", sa.Uuid(), nullable=True),
        sa.Column("target_agent_id", sa.Uuid(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_post_id"],
            ["posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interactions_agent_id"), "interactions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_interactions_run_id"), "interactions", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interactions_run_id"), table_name="interactions")
    op.drop_index(op.f("ix_interactions_agent_id"), table_name="interactions")
    op.drop_table("interactions")
    op.drop_index(op.f("ix_posts_run_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_round_number"), table_name="posts")
    op.drop_index(op.f("ix_posts_root_post_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_author_agent_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_llm_calls_run_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_follows_run_id"), table_name="follows")
    op.drop_index(op.f("ix_follows_follower_agent_id"), table_name="follows")
    op.drop_index(op.f("ix_follows_followed_agent_id"), table_name="follows")
    op.drop_table("follows")
    op.drop_index(op.f("ix_run_seeds_run_id"), table_name="run_seeds")
    op.drop_table("run_seeds")
    op.drop_index(op.f("ix_analysis_reports_run_id"), table_name="analysis_reports")
    op.drop_table("analysis_reports")
    op.drop_index(op.f("ix_agents_run_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_handle"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("runs")
    # ### end Alembic commands ###
